package Presentacion;

import Datos.dTipoTradiciones;
import Logica.fTipoTradiciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class frmTipoTradicion extends javax.swing.JFrame {

    /**
     * Creates new form frmTipoTradicion
     */
    public frmTipoTradicion() {
        initComponents();
        mostrar("");
        
    }

    
    void mostrar(String buscar) {

        try {
            DefaultTableModel modelo;
            fTipoTradiciones func = new fTipoTradiciones();

            modelo = func.mostrar(buscar);

            dgv_Tabla_TT.setModel(modelo);

            lblRegistrosTT.setText("Registros: " + Integer.toString(func.total_registros));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }

    }
    
    
    void borrarDatos_txt(){
        
        txtId_TTradicion.setText("");
        txtNomTTradicion.setText("");
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomTTradicion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId_TTradicion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgv_Tabla_TT = new javax.swing.JTable();
        btnAgregarTT = new javax.swing.JButton();
        btnModificarTT = new javax.swing.JButton();
        btnEliminarTT = new javax.swing.JButton();
        btnCancelarTT = new javax.swing.JButton();
        lblRegistrosTT = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipo de Tradiciones");
        setResizable(false);

        jLabel1.setText("Tipo Tradicion");

        jLabel2.setText("Clave");

        dgv_Tabla_TT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dgv_Tabla_TT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgv_Tabla_TTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgv_Tabla_TT);

        btnAgregarTT.setText("Agregar");
        btnAgregarTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTTActionPerformed(evt);
            }
        });

        btnModificarTT.setText("Modificar");
        btnModificarTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTTActionPerformed(evt);
            }
        });

        btnEliminarTT.setText("Eliminar");
        btnEliminarTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTTActionPerformed(evt);
            }
        });

        btnCancelarTT.setText("Cancelar");
        btnCancelarTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTTActionPerformed(evt);
            }
        });

        lblRegistrosTT.setText("jLabel3");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomTTradicion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId_TTradicion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarTT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarTT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelarTT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarTT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRegistrosTT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_TTradicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomTTradicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarTT)
                    .addComponent(btnAgregarTT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarTT)
                    .addComponent(btnEliminarTT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(lblRegistrosTT))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTTActionPerformed
        // TODO add your handling code here:
        
        if (txtId_TTradicion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un identificador");
            txtId_TTradicion.requestFocus();
            return;
        }

        if (txtNomTTradicion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un nombre de un tipo de tradicion");
            txtNomTTradicion.requestFocus();
            return;
        }

        dTipoTradiciones dts = new dTipoTradiciones();
        fTipoTradiciones func = new fTipoTradiciones();

        dts.setId_Tipo_Tradicion(txtId_TTradicion.getText());
        dts.setNombre_Tipo_Tradicion(txtNomTTradicion.getText());

        func.insertar(dts);
        mostrar("");
        borrarDatos_txt();
    }//GEN-LAST:event_btnAgregarTTActionPerformed

    private void btnEliminarTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTTActionPerformed
        // TODO add your handling code here:
        
        if (!txtId_TTradicion.getText().equals("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de eliminar el registro?", "Confirmar", 2);

            if (confirmacion == 0) {

                fTipoTradiciones func = new fTipoTradiciones();
                dTipoTradiciones dts = new dTipoTradiciones();

                dts.setId_Tipo_Tradicion(txtId_TTradicion.getText());
                func.eliminar(dts);

                mostrar("");
                borrarDatos_txt();
                JOptionPane.showConfirmDialog(rootPane, "Dato Eliminado...");
                

            }
        }
        
        
    }//GEN-LAST:event_btnEliminarTTActionPerformed

    private void dgv_Tabla_TTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgv_Tabla_TTMouseClicked
        // TODO add your handling code here:
        
        
         int fila = dgv_Tabla_TT.rowAtPoint(evt.getPoint());

        txtId_TTradicion.setText(dgv_Tabla_TT.getValueAt(fila, 0).toString());
        txtNomTTradicion.setText(dgv_Tabla_TT.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_dgv_Tabla_TTMouseClicked

    private void btnCancelarTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTTActionPerformed
        // TODO add your handling code here:
        borrarDatos_txt();
    }//GEN-LAST:event_btnCancelarTTActionPerformed

    private void btnModificarTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTTActionPerformed
        // TODO add your handling code here:
        
        
        fTipoTradiciones func = new fTipoTradiciones();
        dTipoTradiciones dts = new dTipoTradiciones();
        
        dts.setId_Tipo_Tradicion(txtId_TTradicion.getText());
        dts.setNombre_Tipo_Tradicion(txtNomTTradicion.getText());

        func.modificar(dts);
        mostrar("");

        if (func.modificar(dts)) {
            JOptionPane.showConfirmDialog(rootPane, "Los datos se modificaron correctamente");
            borrarDatos_txt();

        }
        
        
    }//GEN-LAST:event_btnModificarTTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipoTradicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipoTradicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipoTradicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipoTradicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipoTradicion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTT;
    private javax.swing.JButton btnCancelarTT;
    private javax.swing.JButton btnEliminarTT;
    private javax.swing.JButton btnModificarTT;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTable dgv_Tabla_TT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRegistrosTT;
    private javax.swing.JTextField txtId_TTradicion;
    private javax.swing.JTextField txtNomTTradicion;
    // End of variables declaration//GEN-END:variables
}
